format = """
[ /ᐠ - ˕ -マ ](bg:#282C34 fg:#E3E3E3)\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$python\
$cmake\
$golang\
$java\
$kotlin\
$lua\
$cmd_duration\
\n$time $character"""

[git_branch]
symbol = "↑ "

[cmake]
format = "via [c ]($style)"

[golang]
format = 'via [go ]($style)'

[java]
format = 'via [java ]($style)'

[kotlin]
format = 'via [kt ]($style)'

[lua]
format = 'via [lua ]($style)'

[nodejs]
format = 'via [node ](#7AFF8E)'

[python]
format = 'via [py ](#FDF68B)'

[rust]
format = 'via [rs ]($style)'

[directory]
format = "[ $path ](#85A0FF)"
truncation_length = 3
truncation_symbol = "/"

[git_status]
format = '([$all_status$ahead_behind](#FF8FAB) )'
unstaged = '[✘ $count](#FDF68B)'
staged = '[+\($count\)](#7AFF8E)'
deleted = '[✘ $count ](#FF5564)'
conflicted = ''
ahead = ''
behind = ''
modified = ''

[cmd_duration]
format = 'took [$duration](#FDF68B) '

[time]
disabled = false
time_format = "%I:%M %p" # Hour:Minute AM/PM Format
format = '[$time](white)'