# ^.,.^ - maow!

[battery]
full_symbol = "‚Ä¢"
charging_symbol = "‚á°"
discharging_symbol = "‚á£"

[git_branch]
symbol = "‚Üë "

[bun]
format = "via [bun ]($style)"

[buf]
format = "via [buf ]($style)"

[cmake]
format = "via [c ]($style)"

[cobol]
format = "via [cobol ]($style)"

[crystal]
format = "via [crystal ]($style)"

[daml]
format = "via [daml ]($style)"

[dart]
format = "via [dart ]($style)"

[deno]
format = "via [deno ]($style)"

[dotnet]
format = "[$symbol(üéØ $tfm )]($style)"

[elixir]
format = 'via [elixir ]($style)'

[elm]
format = 'via [elm ]($style)'

[erlang]
format = 'via [erlang ]($style)'

[fennel]
format = 'via [fennel ]($style)'

[golang]
format = 'via [golang ]($style)'

[gradle]
format = 'via [gradle ]($style)'

[haxe]
format = 'via [haxe ]($style)'

[helm]
format = 'via [helm ]($style)'

[java]
format = 'via [java ]($style)'

[julia]
format = 'via [julia ]($style)'

[kotlin]
format = 'via [kotlin ]($style)'

[lua]
format = 'via [lua ]($style)'

[meson]
format = 'via [meson ]($style)'

[nim]
format = 'via [nim ]($style)'

[nodejs]
format = 'via [node ]($style)'

[ocaml]
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'

[opa]
format = 'via [opa ]($style)'

[perl]
format = 'via [perl ]($style)'

[php]
format = 'via [php ]($style)'

[pulumi]
format = 'via [pulumi ]($style)'

[purescript]
format = 'via [pursescript ]($style)'

[python]
format = 'via [py ]($style)'

[raku]
format = 'via [raku ]($style)'

[red]
format = 'via [red ]($style)'

[rlang]
format = 'via [rlang ]($style)'

[ruby]
format = 'via [ruby ]($style)'

[rust]
format = 'via [rs ]($style)'

[solidity]
format = 'via [solidity ]($style)'

[swift]
format = 'via [swift ]($style)'

[vagrant]
format = 'via [vagrant ]($style)'

[vlang]
format = 'via [vlang ]($style)'

[zig]
format = 'via [zig ]($style)'


[directory]
format = "[/·ê† - Àï -„Éû $path ]($style)"
truncation_length = 3
truncation_symbol = "/"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
untracked = '[‚úò $count](yellow)'
staged = '[+\($count\)](green)'
deleted = '[‚úò $count ](red)'
conflicted = ''
ahead = ''
behind = ''
modified = ''

[time]
disabled = false
time_format = "%I:%M %p" # Hour:Minute AM/PM Format
format = '[$time](white) '