# ^..^ ~ made by sebiram

format = """
[ /ᐠ - ˕ -マ ](bg:#282C34 fg:#E3E3E3)\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$python\
$cmake\
$golang\
$java\
$kotlin\
$lua\
$cmd_duration\
\n $character"""

[git_branch]
symbol = "↑ "

[cmake]
format = 'via [clang ]($style)'

[golang]
format = 'via [go ]($style)'

[java]
format = 'via [java ]($style)'

[kotlin]
format = 'via [kt ]($style)'

[lua]
format = 'via [lua ]($style)'

[nodejs]
format = 'via [node ](#88f75c)'

[python]
format = 'via [py ](#ffd343)'

[rust]
format = 'via [rs ](#CE422B)'

[cmd_duration]
format = 'took [$duration - meow](#Fee7aa) '

[directory]
format = "[ $path ](#85A0FF)"
truncation_length = 3
truncation_symbol = "/"

[git_status]
format = "[$all_status$ahead_behind](#FF8FAB)"
modified = '[M-$count ](#Fee7aa)'
deleted = '[D-$count ](#FF5564)'
untracked = '[U-$count ](#ffb16e)'
staged = '[S-$count ](#7AFF8E)'
diverged = ''
conflicted = ''
ahead = ''
behind = ''

[character]
success_symbol = '[=^..^=](#7AFF8E)'
error_symbol = '[=^..^=](#FF5564)'